name = "twoflags"
type = "javascript"
main = "./build/index.js"
workers_dev = true
compatibility_date = "2022-04-05"

[env.api]
kv-namespaces = [
  { binding = "ENVIRONMENTS", id = "7c76648b4cd544eb9783394a1140191c" },
	{ binding = "APIKEYS", id = "79e7ac905f734626b42782c1dc8be4db" },
	{ binding = "APIKEY", id = "96a692f36f1b4d5480ce89bd3b31e165" },
	{ binding = "FLAGS", id = "7527db3f482a40a6bc0e072a6a977d5d" },
	{ binding = "NAMESPACES", id = "0e540635f4a3416f8ce36e16c2645d5a" },
	{ binding = "SEGMENTS", id = "2587f2e5d51a4e8e9e530ac77d468900" },
	{ binding = "SELECTORS", id = "15bf9bcffa2140bcb9e65c5efa44e014" },
	{ binding = "ACCOUNTS", id = "0a7eab4378a84d21af2b03ec06f34376" },
	{ binding = "VALUES", id = "b7f6472131db4c5ebdee0f2e5174ab1a" },
	{ binding = "RESOLVER", id = "dacf6a9c5af94416b8efccdf78106daf" }
]

[env.resolver]
kv-namespaces = [
	{ binding = "SEGMENTS", id = "2587f2e5d51a4e8e9e530ac77d468900" },
	{ binding = "RESOLVER", id = "dacf6a9c5af94416b8efccdf78106daf" }
]
