name: Deploy to Cloudflare

on:
  push:
    branches:
      - master

jobs:
  deploy-api:
    name: Deploying twoflags
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    env:
      CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - run: yarn
    - run: yarn build:api
    - run: yarn publish:api
    - run: yarn build:resolver
    - run: yarn publish:resolver
